function [xi_minus,xi_plus,W,J,A,q,d,b,omegabar]=problem(t,pr,X,c,theta)
om=oomega(t);
q=pr(om*t); %insurance prices
A=-X(om*t)'; %marketed space
n=length(q);
payoff=A*theta;
b=min(payoff,-c);
xi_plus=payoff./A';
xi_minus=zeros(n,1);
omegabar=1e100;
W=zeros(n);
J=[];
d=[];